name: Vik's Blog
description: Writings on machine learning, data science, and other cool stuff
meta_description: "Vik's Blog -- exciting projects in machine learning"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.vikparuchuri.com'
exclude:
  - python
permalink: /blog/:title/
rss_name: atom.xml

# Details for the RSS feed generator
url:            'www.vikparuchuri.com'
author:         'Vik Paruchuri'
